### ISSUE TITLE
compression 0.1.4 doesn't build on Max OSX 10.13.6

### ISSUE THREAD

**Issue by crusty-dave** [chalharu/rust-compression#29]
error[E0432]: unresolved import `log::Level`
  --> /Users/.cargo/registry/src/github.com-1ecc6299db9ec823/compression-0.1.4/src/bzip2/encoder.rs:30:5
   |
30 | use log::Level;
   |     ^^^^^^^^^^ no `Level` in the root

**Comment by crusty-dave** [comment]
Sorry, my bad, I forgot to do cargo update after updating rustc from 1.35.0 to 1.38.0.
